events { worker_connections 1024; }

http {
    upstream backendbank {
        server host.docker.internal:8080; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backendbank;
            proxy_read_timeout 3s;
            proxy_connect_timeout 3s;
        }
    }
}


